scripts: Add missing env vars to enable anon auth when push=false
This commit adds two missing environment variables that allow for
anonymous authentication to remote registries when pushing build results
is disabled. Pulls and remote digest checks are read-only operations
that do not require credentials, however however, if credentials are not
set during a non-push build, some steps may return an error that looks
like this:

```
sha256:0e59c8168a48aa9ed0573be2d38d40a95e1b1635877d6e3dd56dfd33e3597e56
pulling image moby/buildkit:buildx-stable-1 done
ERROR: error getting credentials - err: exit status 1, out: `ANY_REGISTRY_USERNAME is not set`
```

The above example was triggered while building the `image-maker` image
in the call to `docker buildx build`. This bug prevents PRs from forks
from running the "Build all images" workflow to test their changes, making
it more difficult for members of the community who don't have write access
to this repository to open PRs.

Signed-off-by: Ryan Drew <ryan.drew@isovalent.com>